# Generated by Django 6.0.2 on 2026-02-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_barangay_barangay_id_municipality_muncity_id_and_more'),
        ('verifier', '0002_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifier',
            name='assigned_municipalities',
            field=models.ManyToManyField(related_name='verifiers', to='location.municipality'),
        ),
    ]
