# Generated by Django 6.0.2 on 2026-02-09 05:43

import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_barangay_barangay_id_municipality_muncity_id_and_more'),
        ('verifier', '0003_verifier_assigned_municipalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifier',
            name='assigned_barangays',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='assigned_municipalities', chained_model_field='municipality', related_name='verifiers', to='location.barangay'),
        ),
    ]
