# Generated by Django 6.0.2 on 2026-02-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_barangay_barangay_id_municipality_muncity_id_and_more'),
        ('verifier', '0004_alter_verifier_assigned_barangays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifier',
            name='assigned_barangays',
            field=models.ManyToManyField(related_name='verifiers', to='location.barangay'),
        ),
    ]
